export const ProfileStyles = {
  container: 'max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-lg',
  header: 'flex justify-between items-center mb-8 pb-4 border-b-2 border-gray-200',
  title: 'text-3xl font-bold text-gray-800',
  badge: 'px-4 py-2 bg-[#ffdbbb] text-gray-800 rounded-full font-medium text-sm',
  section: 'mb-8',
  sectionHeader: 'flex justify-between items-center mb-4',
  sectionTitle: 'text-xl font-semibold text-gray-700',
  buttonGroup: 'flex gap-2',
  grid: 'grid grid-cols-1 md:grid-cols-2 gap-4',
  field: 'flex flex-col sm:flex-row sm:items-center py-2 border-b border-gray-100',
  label: 'font-medium text-gray-600 min-w-[150px] mb-1 sm:mb-0',
  value: 'text-gray-800 break-words',
  loadingSpinner: 'flex justify-center items-center py-12 text-lg text-gray-600',
  error: 'bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-center',
}; 